name: Build www

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 14
        uses: actions/setup-node@v4
        with:
          node-version: "14"
          cache: "npm"

      - name: Install deps
        run: |
          npm config set fund false
          npm config set audit false
          npm ci --no-audit --no-fund || npm i --no-audit --no-fund --legacy-peer-deps || npm i --no-audit --no-fund --force

      - name: Build
        run: npm run build

      - name: Zip www
        run: |
          cd www
          zip -r ../www.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-bot-www
          path: www.zip
